version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 891377085221.dkr.ecr.eu-west-2.amazonaws.com
      - REPOSITORY_URI=891377085221.dkr.ecr.eu-west-2.amazonaws.com/hive-web
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date` for $ASPNETCORE_ENVIRONMENT
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .     
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"hive-web","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
    files: 
      - 'imagedefinitions.json'
      - 'imageDetail.json'
      - 'taskdefdevelopment.json'
      - 'taskdefstaging.json'
      - 'taskdefproduction.json'
      - 'appspec.yml'