AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate + Load Balancer running a .NET Web API container from ECR

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for deployment
    Default: "vpc-0762bfea42ac35503"
  SubnetIds:
    Type: CommaDelimitedList
    Description: List of public subnet IDs
    Default: "subnet-0aa1a709079c0d2ef,subnet-006f1f9414204e130,subnet-09c85c490603a1ee6"
  ECRImageUri:
    Type: String
    Description: ECR Image URI (e.g., 1234567890.dkr.ecr.us-east-1.amazonaws.com/myapp:latest)
    Default: "891377085221.dkr.ecr.eu-west-2.amazonaws.com/hive-web:latest"
  EnvironmentName:
    Type: String
    Description: The deployment envrionment
    Default: production
  InfraStack:
    Type: String
    Description: The stack used for the Infra
    Default: hive-core

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub web1-${EnvironmentName}
      Port: 8080
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 90
      HealthCheckTimeoutSeconds: 20
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-299
      Tags:
        - Key: System
          Value: Hive
        - Key: Environment
          Value: !Ref EnvironmentName

  TargetGroup2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub web2-${EnvironmentName}
      Port: 8081
      Protocol: HTTP
      VpcId: !Ref VpcId 
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 90
      HealthCheckTimeoutSeconds: 20
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-299
      Tags:
        - Key: System
          Value: Hive
        - Key: Environment
          Value: !Ref EnvironmentName

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: 
        Fn::ImportValue:
          Fn::Sub: "${InfraStack}-${EnvironmentName}-LoadBalancerARN"
      Port: 49160
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  TestListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: 
        Fn::ImportValue:
          Fn::Sub: "${InfraStack}-${EnvironmentName}-LoadBalancerARN"
      Port: 49161
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup2

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub hive-web-${EnvironmentName}
      Cpu: "256"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: hive-web
          Image: !Ref ECRImageUri
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "true"
              awslogs-region: eu-west-2
              awslogs-stream-prefix: ecs
              awslogs-group: !Sub ecs-hive-web-${EnvironmentName}
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
          Environment:
            - Name: ASPNETCORE_ENVIRONMENT
              Value: !Sub "${EnvironmentName}"
            - Name: ASPNETCORE_URLS
              Value: http://+:8080
          Ulimits:
            - Name: nofile
              SoftLimit: 1048576
              HardLimit: 1048576
    # NOTE: TaskDefinition doesn't support tags directly in CloudFormation

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub hive-web-ecs-task-${EnvironmentName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ECSLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      Cluster: 
        Fn::ImportValue:
          Fn::Sub: "${InfraStack}-${EnvironmentName}-ECSCluster"
      LaunchType: FARGATE
      DesiredCount: 1
      ServiceName: !Sub hive-web-${EnvironmentName}
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref ECSTaskSecurityGroup
      LoadBalancers:
        - ContainerName: !Sub hive-web
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup
      TaskDefinition: !Ref TaskDefinition
      DeploymentController:
        Type: CODE_DEPLOY
      Tags:
        - Key: System
          Value: Hive
        - Key: Environment
          Value: !Ref EnvironmentName

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub hive-web-alb-${EnvironmentName}
      GroupDescription: Allow HTTP in and all traffic out
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 49160
          ToPort: 49160
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: System
          Value: Hive
        - Key: Environment
          Value: !Ref EnvironmentName

  ECSTaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub hive-web-ecs-task-${EnvironmentName}
      GroupDescription: Allow traffic from ALB only
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
          # SourceSecurityGroupId: !Ref ALBSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: System
          Value: Hive
        - Key: Environment
          Value: !Ref EnvironmentName

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: ECS
      ApplicationName: hive-core-production

  CodeDeployDeploymentGroup:
    DependsOn: ECSService 
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: !Sub hive-web-dg-${EnvironmentName}
      ServiceRoleArn: arn:aws:iam::891377085221:role/hive-core-deploy-ecs
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
          WaitTimeInMinutes: 0
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - TargetGroups:
              - Name: !Ref TargetGroup
              - Name: !Ref TargetGroup2
            ProdTrafficRoute:
              ListenerArns:
                - !Ref Listener
            TestTrafficRoute:
              ListenerArns:
                - !Ref TestListener
      ECSServices:
        - ClusterName: !Ref ECSCluster
          ServiceName: !Sub hive-web-${EnvironmentName}


# £47.13

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: HiveUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: HiveBlazorAppClient
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - https://hive-core-alb-production-1562672820.eu-west-2.elb.amazonaws.com:49160/signin-oidc
      LogoutURLs:
        - https://hive-core-alb-production-1562672820.eu-west-2.elb.amazonaws.com:49160/signout-callback-oidc
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      AllowedOAuthFlowsUserPoolClient: true

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: hive-blazor-login
      UserPoolId: !Ref CognitoUserPool

Outputs:

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  AppClientId:
    Description: Cognito App Client ID
    Value: !Ref CognitoUserPoolClient

  CognitoDomain:
    Description: Cognito Domain URL
    Value: !Sub "https://${CognitoUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"